[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/home/qbittorrent-nox/.local/share/qBittorrent/logs

[BitTorrent]
Session\DefaultSavePath=/mnt/nvidia-shield/media/downloads
Session\ExcludedFileNames=
Session\Interface=wlan0
Session\InterfaceAddress=192.168.1.121
Session\Port=7272
Session\QueueingSystemEnabled=false
Session\SSL\Port=26549
Session\TempPath=/home/qbittorrent-nox/Downloads/incomplete
Session\TempPathEnabled=true

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false

[Preferences]
MailNotification\req_auth=true
MailNotification\username=admin
WebUI\AuthSubnetWhitelist=@Invalid()

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
